set global startup_info_version 20240519

set global indentwidth 4
set global ui_options terminal_set_title=true terminal_assistant=none terminal_enable_mouse=true
#set global autoinfo ""
set global autocomplete prompt|insert

colorscheme 100r

add-highlighter global/ wrap
add-highlighter global/ show-whitespaces -only-trailing -lf " " -indent ""
add-highlighter global/ number-lines -hlcursor -cursor-separator ' ▶ ' -separator '   '
add-highlighter global/ show-matching

eval %sh{kak-lsp}

set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"

hook global WinSetOption filetype=(go|php) %{
    lsp-enable-window
    lsp-inlay-diagnostics-enable window

    hook window BufWritePre .* lsp-formatting-sync
    hook global BufWritePre .*[.]go %{ try %{
        lsp-code-actions-sync source.organizeImports
    }}
}

def -params 1 project %{ change-directory "%arg{1}" }
complete-command project shell-script-candidates %{ git-projects list }

def mkdir %{ nop %sh{ mkdir -p $(dirname $kak_buffile) } }
def chmod %{ nop %sh{ chmod +x $kak_buffile } }

# i do have a ghost key combination on laptop
def pipe-to -params .. %{ exec <a-|> }

def yank-ref %{
    evaluate-commands -draft %{
        execute-keys ',;x'
        set-register dquote "%val{bufname}:%val{cursor_line}:%val{selection}"
    }
}

def lookup %{ eval %{
    try %{
        eval -draft %{
            exec '<a-i><a-w>S\A(a/|b/)<ret>'
            exec 's\A([^:]+)(?::(\d+))?(?::(\d+))?<ret>'
            set-register a %reg{1} %reg{2} %reg{3}
        }

        eval -try-client %opt{jumpclient} -verbatim -- edit -existing -- %reg{a}
    } catch %{
        exec -draft x<a-!>sh<ret>
    }
}}

def reduce-selections %{
    try %{
        exec -draft "<a-,>"
        exec ","
    } catch %{
        exec ";"
    }
}

# this does not work when trying to open another kak instance in same directory
hook global EnterDirectory .* %{ rename-session %sh{ basename $(pwd) } }

hook global BufOpenFile ^([^*]+)$ %{ evaluate-commands %sh{
    if ! git check-ignore -q "$kak_hook_param_capture_1" 2>/dev/null; then
        for hook in WinCreate BufReload BufWritePost; do
            echo "hook buffer $hook %val{buffile} 'git show-diff'"
        done
    fi
}}

hook global WinSetOption filetype=(go) "set buffer indentwidth 0"
hook global WinSetOption filetype=(html|json|nix|xml|js|ts) "set buffer indentwidth 2"
hook global WinSetOption filetype=(c|zig) "set buffer indentwidth 4"

hook global WinSetOption filetype=git-commit %{
    set window autowrap_column 72
    set window autowrap_format_paragraph true
    autowrap-enable
}

hook global KakBegin .* %{
    set global termcmd 'io.elementary.terminal -n -e'
}

# personal mappings
map global normal <space> ":enter-user-mode lsp<ret>"
map global normal <ret>   ":lookup<ret>"
map global normal <esc>   ":reduce-selections<ret>"
map global normal <c-n>   ":edit -scratch *scratch*<ret>"
map global normal <c-p>   ":git edit<space>"
map global normal <c-f>   ":git grep<space>"
map global normal <s-y>   ":yank-ref<ret>"
map global normal <a-y>   "<a-|>copy<ret>:echo copied to clipboard<ret>"

# reverse prompt mappings
map global prompt <down> <tab>
map global prompt <up>   <s-tab>
map global prompt <c-n>  <down>
map global prompt <c-p>  <up>
