[ids]
# raliance internal keyboard
0001:0001:d651c513

[global]
oneshot_timeout      = 1000
overload_tap_timeout = 1000

[main]
tab = overload(navnum, tab)
backspace = timeout(overloadt2(navnum, backspace, 50), 250, C-backspace)
leftbrace = timeout(overloadt2(navnum, backspace, 50), 250, C-backspace)

capslock   = overload(control, esc)
enter      = overload(control, enter)
apostrophe = overload(control, enter)

rightbrace = noop
backslash  = noop

space = overloadt(navnum, space, 150)

shift      = oneshot(shift)
leftalt    = oneshot(alt)
rightalt   = oneshot(altgr)
leftshift  = oneshot(lshift)
rightshift = oneshot(rshift)

# angle mod
102nd = z
z = x
x = c
c = v
v = b
b = 102nd

[lshift:S]
rightshift = togglem(caps, capslock)

# only put delete on left shift as opposed keys
backspace = delete
leftbrace = delete

[rshift:S]
leftshift = togglem(caps, capslock)

[caps]
capslock   = overload(control, togglem(caps, capslock))
leftshift  = togglem(caps, capslock)
rightshift = togglem(caps, capslock)

[control]
space = layerm(navnum, C-space)
# ^ helpful for tmux prefix

[navnum]
# fine insecable space to chain with numbers
tab = S-space

q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 0

a = oneshot(meta) 
semicolon = oneshot(meta)

d = S-tab
f = tab

h = timeout(left,  250, home)
j = timeout(down,  250, pagedown)
k = timeout(up,    250, pageup)
l = timeout(right, 250, end)

[navnum+control]
h = timeout(C-left,  250, home)
l = timeout(C-right, 250, end)
# ^ easily go to the beginning/end of the line

# favor symbols over numbers
[navnum+altgr]
q = G-q
w = G-w
e = G-e
r = G-r
t = G-t
y = G-y
u = G-u
i = G-i
o = G-o
p = G-p

a = G-a
s = G-s
d = G-d
f = G-f
g = G-g
h = G-h
j = G-j
k = G-k
l = G-l
semicolon = G-semicolon
