[ids]
# raliance internal keyboard
0001:0001:d651c513
0001:0001:a2eea399

[global]
oneshot_timeout      = 1000
overload_tap_timeout = 1000

[main]
backspace = timeout(backspace, 250, C-backspace)
leftbrace = timeout(backspace, 250, C-backspace)

tab        = overload(upper, tab)
capslock   = overload(control, esc)

enter      = overload(control, enter)
apostrophe = overload(control, enter)

rightbrace = noop
backslash  = noop

space = overloadt(upper, space, 150)

shift      = oneshot(shift)
leftalt    = oneshot(alt)
rightalt   = oneshot(altgr)
leftshift  = oneshot(lshift)
rightshift = oneshot(rshift)

# angle mod
102nd = z
z = x
x = c
c = v
v = b
b = 102nd

[lshift:S]
rightshift = togglem(caps, capslock)

# only put delete on left shift as opposed keys
backspace = delete
leftbrace = delete

[rshift:S]
leftshift = togglem(caps, capslock)

[caps]
capslock   = overload(control, togglem(caps, capslock))
leftshift  = togglem(caps, capslock)
rightshift = togglem(caps, capslock)

[control]
# helpful for tmux prefix
space = layerm(navnum, C-space)

[upper:M]
tab = swapm(super, M-tab)

backspace = timeout(backspace, 250, C-backspace)
leftbrace = timeout(backspace, 250, C-backspace)

enter      = overload(control, enter)
apostrophe = overload(control, enter)

space = space

rightalt = overloadi(0, overloadt(altgr, 0, 150), 150)
m = overloadi(1, timeout(1, 250, swapm(super, M-1)), 150)
, = overloadi(2, timeout(2, 250, swapm(super, M-2)), 150)
. = overloadi(3, timeout(3, 250, swapm(super, M-3)), 150)
j = overloadi(4, timeout(4, 250, swapm(super, M-4)), 150)
k = overloadi(5, timeout(5, 250, swapm(super, M-5)), 150)
l = overloadi(6, timeout(6, 250, swapm(super, M-6)), 150)
u = overloadi(7, timeout(7, 250, swapm(super, M-7)), 150)
i = overloadi(8, timeout(8, 250, swapm(super, M-8)), 150)
o = overloadi(9, timeout(9, 250, swapm(super, M-9)), 150)

n = dot
semicolon = S-dot

# fine insecable space to chain with numbers
p = S-space

e = timeout(up,    250, swapm(super, M-up))
s = timeout(left,  250, swapm(super, M-left))
d = timeout(down,  250, swapm(super, M-down))
f = timeout(right, 250, swapm(super, M-right))

w = home
r = end
t = pageup
g = pagedown

y = timeout(S-tab, 250, swapm(super, M-S-tab))
h = timeout(tab,   250, swapm(super, M-tab))

[upper+control]
# easily go to the beginning/end of the line
s = timeout(C-left,  250, home)
f = timeout(C-right, 250, end)

[upper+altgr]
# favor symbols over numbers
q = G-q
w = G-w
e = G-e
r = G-r
t = G-t
y = G-y
u = G-u
i = G-i
o = G-o
p = G-p
a = G-a
s = G-s
d = G-d
f = G-f
g = G-g
h = G-h
j = G-j
k = G-k
l = G-l
; = G-semicolon
102nd = G-z
z = G-x
x = G-c
c = G-v
v = G-b
n = G-n
m = G-m
, = G-comma
. = G-dot

[super:M]
tab = M-tab

rightalt = overloadt2(altgr, M-0, 150)
m = M-1
, = M-2
. = M-3
j = M-4
k = M-5
l = M-6
u = M-7
i = M-8
o = M-9

e = M-up
s = M-left
d = M-down
f = M-right

y = M-S-tab
h = M-tab 

[super+control]
# easily chain tab switching after desktop switching
y = C-S-tab
h = C-tab
