[ids]
# raliance internal keyboard
0001:0001:d651c513
0001:0001:a2eea399

[global]
default_layout = anglemod

oneshot_timeout      = 1000
overload_tap_timeout = 1000

[anglemod:layout]
102nd = z
z = x
x = c
c = v
v = b
b = setlayout(main)

[main]
tab        = overload(numpad, tab)
capslock   = overload(control, esc)
apostrophe = overload(control, enter)

leftbrace  = backspace
rightbrace = noop
backslash  = noop

space = overloadt(upper, space, 150)

shift      = oneshot(shift)
leftalt    = oneshot(alt)
rightalt   = oneshot(altgr)
leftshift  = oneshot(lshift)
rightshift = oneshot(rshift)
leftmeta   = oneshot(meta)

# to enable anglemod if it has been disabled
102nd = setlayout(anglemod)

[lshift:S]
rightshift = togglem(caps, capslock)

# only put delete on left shift as opposed keys
backspace = delete
leftbrace = delete

[rshift:S]
leftshift = togglem(caps, capslock)

[caps]
capslock   = overload(control, togglem(caps, capslock))
leftshift  = togglem(caps, capslock)
rightshift = togglem(caps, capslock)

[control]
# helpful for tmux prefix
space = layerm(navnum, C-space)

[numpad]
rightalt = overloadt(altgr, 0, 150)
m = 1
, = 2
. = 3
j = 4
k = 5
l = 6
u = 7
i = 8
o = 9

[upper]
h = swapm(scroll, left)
j = swapm(scroll, down)
k = swapm(scroll, up)
l = swapm(scroll, right)

f = C-tab
d = C-S-tab

[upper+meta]
# avoid swapping to scroll to chain
# workspace switching and tab switching
h = M-left
j = M-down
k = M-up
l = M-right

[scroll]
h = left
j = down
k = up
l = right

f = pagedown
d = pageup

[scroll+control]
j = end
k = home
